# Generated by Django 2.2.2 on 2019-06-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='site_name',
            field=models.CharField(max_length=100, verbose_name='Site Name'),
        ),
    ]
